name: Docker Image CI

on:
  push:
    branches:
    - stable
  schedule:
  - cron: '0 12 15 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - tag: 3.8-alpine3.12
          directory: alpine
        - tag: 3.8-slim-buster
          directory: debian
    steps:
    - uses: actions/checkout@v2
    - name: Set date
      id: date
      run: echo "::set-output name=date::$(date --iso-8601=date)"
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: midnighter/pip-compile
        tags: ${{ matrix.tag }},${{ matrix.tag }}_${{ steps.date.outputs.date }}
        path: ${{ matrix.directory }}
        build_args: TAG=${{ matrix.tag }}
        labels: org.opencontainers.image.authors=midnighter@posteo.net,org.opencontainers.image.vendor=Moritz E. Beber,org.opencontainers.image.licenses=Apache-2.0
        add_git_labels: true
